name: flutter_audio_capture
description: Capture the audio buffer stream through microphone for iOS/Android.
version: 1.0.0
homepage: https://github.com/ysak-y/flutter_audio_capture

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.5
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        pluginClass: FlutterAudioCapturePlugin
        package: com.ymd.flutter_audio_capture
      ios: 
        pluginClass: FlutterAudioCapturePlugin
      linux: 
        pluginClass: FlutterAudioCapturePlugin
