name: flutter_audio_capture
description: Capture the audio buffer stream through microphone for iOS/Android.
version: 1.1.12
homepage: https://github.com/ysak-y/flutter_audio_capture

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.5
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ymd.flutter_audio_capture
        pluginClass: FlutterAudioCapturePlugin
      ios:
        pluginClass: FlutterAudioCapturePlugin
      linux:
        pluginClass: FlutterAudioCapturePlugin
